### ISSUE TITLE
T-Watch 2020 v3 - firmware 22 - ENODEV ?

### ISSUE THREAD

**Issue by Reverendissimo** [jeffmer/TTGO-T-watch-2020-Micropython-OS#23]
hello guys,
gotta problem here.
im installing firmware 22,
compiling everything with mpy-cross-v6.2 -march=xtensawin in compile.sh
upload all with the install.sh 
try to import loader (i commented the boot.py to debug)
>>> import loader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./loader.py", line 2, in <module>
  File "./tempos.py", line 175, in <module>
  File "./drivers/ft6236.py", line 22, in __init__
  File "./drivers/ft6236.py", line 59, in enable
  File "./drivers/ft6236.py", line 31, in writeByte
OSError: [Errno 19] ENODEV

hurm?

**Comment by jeffmer** [comment]
It may be that the chip is not getting power from the axp202 which can get into an odd state. Try taking the battery out and this making sure everything is hard reset.

**Comment by Reverendissimo** [comment]
it is connected with USB, battery turned off. looks like the pin assignment is wrong in the tempos.py
# touch controller
I2C0 = I2C(0, scl=Pin(32), sda=Pin(23), freq=400000)
**tp = Pin(38, Pin.IN)**
tc = FT6236(I2C0, tp)

that tp should it be interrupt or reset?
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/82f286ae3eb6b6d3a6b09bb7254ecbd6fb370670/docs/watch_2020_v3.md


accroding to this:

FT6336 RST | 14
FT6336 Interrupt | 38

**Comment by jeffmer** [comment]
Tp = 38 is the touch interrupt pin

I have got V1 and V2 watches. You have V3 and it has the reset pin =14. The I2C pins are the same. 

PS make sure you have V3 set in the config.py file.

**Comment by Reverendissimo** [comment]
roger that, i'll try to turn on the battery switch, maybe it's just the usb not delivering enough juice.
if u need a v3 for debug purpose hit me up if i can help.
