### ISSUE TITLE
Copying Images taking FOREVER

### ISSUE THREAD

**Issue by aparker21** [jeffmer/TTGO-T-watch-2020-Micropython-OS#27]
I ran the install.sh and everything was going well until it go to "cp images/dail.png  :images/dial.png"  It says " . . .  copying   9% [#----------]"  and it has been like this for about 30 minutes so far.  Is this normal??

**Comment by jeffmer** [comment]
It should not take that long. It has probably disconnected or crashed in some way. You can copy files manually using Thonny to patch things up such as changing the background png for a watch app. You should be able to mount the watch device on Thonny and look at the directories and files. 

BTW Impressed that you got some useful advice from ChatGPT.

**Comment by aparker21** [comment]
I was pretty impressed as well.  It got me going perfectly!  I went ahead and unplugged and re-plugged the watch and it looks like everything finished but the watch did not boot.  I ran the install.sh again as it didin't seem like the dial.png that it got stuck on downloaded. . . and I was correct and it also missed a few other .png files, but everything installed this time. . . but I still can't get the phone to boot. 
 
 I can comment out the import loader in the boot.py file, but what does this mean: 

"Then, using REPL type import tempos which should load all the drivers and - after a delay - display Loading ... on the watch screen."

How do I do this?

**Comment by aparker21** [comment]
Ok. . . I think I figured out how to get into REPL thanks to chatGPT.  I have done so and typed import tempos and I get the following: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./tempos.py", line 3, in <module>
  File "./drivers/st7789.py", line 16, in <module>
ValueError: incompatible .mpy file

What are my steps to rectify this?  I just installed mpremote and mpy-cross today so they are the most up-to-date.  Do I need to type "install tempos.mpy" ? It appears it is looking for a compatible .mpy file inside the .py file instead of the .mpy file.  Am I understanding that correctly?

**Comment by aparker21** [comment]
I am also getting these problems in the st7789.py driver 

Import "micropython" could not be resolved [Ln 11, Col6]
Import "machine" could not be resolved [Ln12, Col6]
Import "framebuf" could not be resolved [Ln15, Col 8]

**Comment by jeffmer** [comment]
The error is an incompatibility in the graphics.mpy file. This file uses an micropython.viper directive which requires the cross compiler to pick up the correct architecture option. That is in compile.sh there is a -march=xtensawin option.  Either check this is being picked up by the cross compiler or you can delete the viper directive. The graphics will still work but will be slower.

**Comment by jeffmer** [comment]
The import errors may be caused by the same thing.

**Comment by aparker21** [comment]
Cross="my_mpy_cross_path -march=xtensawin"

**Comment by aparker21** [comment]
I saw another issue talking about fixing the viper issue, but I am not fully following what they did to fix it.  Would you mind (when you have a free moment) listing out how I can get the graphics.py recompiled and get the viper working?  I can start from square one if I need as this watch is just a black screen right now anyway.  Again, I am running the V3 watch.

**Comment by jeffmer** [comment]
At the command line type

"your path"/mpy-cross -march=xtensawin graphics.py


This will produce graphics.mpy which you can copy to the watch.

**Comment by jeffmer** [comment]
Also you check the version of the cross compiler with

 "your path"/mpy-cross -version
